#!/bin/sh
#
# platform.sh
# Copyright (C) 2019 Jan-Piet Mens <jpmens@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#

# Linux
if [ -f /etc/os-release ]; then
	. /etc/os-release
	echo "${ID}${VERSION_ID}"
	exit
fi

# macOS
if [ -x /usr/bin/sw_vers ]; then
	echo "macOS$(/usr/bin/sw_vers -productVersion | awk -F. '{print $1}')"
	exit
fi

# FreeBSD

if [ -x /bin/freebsd-version ]; then
	echo "FreeBSD$(/bin/freebsd-version | sed 's/-.*//')"
	exit
fi

# OpenBSD, ...
if [ -x /usr/bin/uname ]; then
	/usr/bin/uname
else
	/bin/uname
fi

