ARG BASE_IMAGE

FROM ${BASE_IMAGE} AS debian-build

RUN apt-get update && apt-get upgrade

# Build foundation and header files
RUN apt-get install --yes --no-install-recommends \
    apt-utils git nano \
    build-essential pkg-config libssl-dev


FROM debian-build

# FPM
RUN apt-get install --yes --no-install-recommends \
    ruby ruby-dev && \
    gem install fpm --version 1.11.0
